---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: squadron
  name: squadron
spec:
  replicas: 3
  selector:
    matchLabels:
      app: squadron
  template:
    metadata:
      labels:
        app: squadron
    spec:
      containers:
      - image: nginx
        name: tie-fighter
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
        envFrom:
        - configMapRef:
            name: tie-systems
        env:
        - name: TARGETING_AI
          valueFrom:
            secretKeyRef:
              name: tie-weapons
              key: targetingAI
        - name: FIRE_CONTROL_KEY
          valueFrom:
            secretKeyRef:
              name: tie-weapons
              key: fireControlKey